# Generated by Django 5.2.15 on 2026-06-26 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0002_revision_notes_alter_auditevent_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('project_created', 'Projekt angelegt'), ('part_created', 'Teil angelegt'), ('revision_uploaded', 'Revision hochgeladen'), ('revision_released', 'Revision freigegeben'), ('revision_downloaded', 'Revision heruntergeladen'), ('revision_notes_updated', 'Revisionsnotiz geaendert'), ('project_snapshot_created', 'Projektstand angelegt')], max_length=40),
        ),
        migrations.CreateModel(
            name='ProjectSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_project_snapshots', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='plm.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSnapshotEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshot_entries', to='plm.revision')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='plm.projectsnapshot')),
            ],
            options={
                'ordering': ['path'],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'path'), name='unique_path_per_project_snapshot')],
            },
        ),
    ]
