# Generated by Django 5.2.15 on 2026-06-27 13:59

import django.db.models.deletion
import plm.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0003_alter_auditevent_action_projectsnapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('project_created', 'Projekt angelegt'), ('part_created', 'Teil angelegt'), ('revision_uploaded', 'Revision hochgeladen'), ('revision_released', 'Revision freigegeben'), ('revision_downloaded', 'Revision heruntergeladen'), ('revision_notes_updated', 'Revisionsnotiz geaendert'), ('project_snapshot_created', 'Projektstand angelegt'), ('export_job_created', 'Exportjob angelegt'), ('export_job_failed', 'Exportjob fehlgeschlagen'), ('revision_artifact_created', 'Revisionsartefakt angelegt')], max_length=40),
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('inspect', 'FreeCAD-Analyse'), ('export', 'Export'), ('png_views', 'PNG-Ansichten')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Wartend'), ('running', 'Laeuft'), ('succeeded', 'Erfolgreich'), ('failed', 'Fehlgeschlagen')], default='queued', max_length=20)),
                ('export_format', models.CharField(blank=True, choices=[('step', 'STEP'), ('stl', 'STL'), ('3mf', '3MF')], max_length=10)),
                ('selected_objects', models.JSONField(blank=True, default=list)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('log', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_export_jobs', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_jobs', to='plm.revision')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevisionArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact_type', models.CharField(choices=[('step', 'STEP'), ('stl', 'STL'), ('3mf', '3MF'), ('png', 'PNG')], max_length=10)),
                ('view_name', models.CharField(blank=True, max_length=40)),
                ('file', models.FileField(upload_to=plm.models.revision_artifact_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='plm.exportjob')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='plm.revision')),
            ],
            options={
                'ordering': ['revision__part__project__code', 'revision__part__number', 'artifact_type', 'view_name', 'created_at'],
            },
        ),
    ]
