# Generated by Django 5.2.15 on 2026-06-28 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0004_alter_auditevent_action_exportjob_revisionartifact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('project_created', 'Projekt angelegt'), ('part_created', 'Teil angelegt'), ('revision_uploaded', 'Revision hochgeladen'), ('revision_released', 'Revision freigegeben'), ('revision_downloaded', 'Revision heruntergeladen'), ('revision_notes_updated', 'Revisionsnotiz geaendert'), ('project_snapshot_created', 'Projektstand angelegt'), ('export_job_created', 'Exportjob angelegt'), ('export_job_failed', 'Exportjob fehlgeschlagen'), ('revision_artifact_created', 'Revisionsartefakt angelegt'), ('checkout_created', 'Checkout angelegt'), ('checkout_canceled', 'Checkout abgebrochen'), ('checkout_completed', 'Checkout eingecheckt'), ('annotation_created', 'Anmerkung angelegt'), ('annotation_updated', 'Anmerkung geaendert')], max_length=40),
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_name', models.CharField(blank=True, max_length=200)),
                ('subelement', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Offen'), ('resolved', 'Erledigt')], default='open', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_annotations', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='plm.part')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='plm.project')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='plm.revision')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('completed', 'Eingecheckt'), ('canceled', 'Abgebrochen')], default='active', max_length=20)),
                ('workspace_hint', models.CharField(blank=True, max_length=500)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('base_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='plm.revision')),
                ('checked_out_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to=settings.AUTH_USER_MODEL)),
                ('completed_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_checkouts', to='plm.revision')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='plm.part')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='plm.projectsnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('part',), name='unique_active_checkout_per_part')],
            },
        ),
    ]
