# Generated by Django 5.2.15 on 2026-06-28 20:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0005_alter_auditevent_action_annotation_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('running', 'Laufend'), ('completed', 'Abgeschlossen'), ('idea', 'Idee'), ('important', 'Wichtig'), ('order', 'Auftrag')], default='running', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('project_created', 'Projekt angelegt'), ('project_updated', 'Projekt geaendert'), ('part_created', 'Teil angelegt'), ('revision_uploaded', 'Revision hochgeladen'), ('revision_released', 'Revision freigegeben'), ('revision_downloaded', 'Revision heruntergeladen'), ('revision_notes_updated', 'Revisionsnotiz geaendert'), ('project_snapshot_created', 'Projektstand angelegt'), ('export_job_created', 'Exportjob angelegt'), ('export_job_failed', 'Exportjob fehlgeschlagen'), ('revision_artifact_created', 'Revisionsartefakt angelegt'), ('checkout_created', 'Checkout angelegt'), ('checkout_canceled', 'Checkout abgebrochen'), ('checkout_completed', 'Checkout eingecheckt'), ('annotation_created', 'Anmerkung angelegt'), ('annotation_updated', 'Anmerkung geaendert')], max_length=40),
        ),
    ]
