# Generated by Django 5.2.15 on 2026-06-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0006_project_project_date_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('project_created', 'Projekt angelegt'), ('project_updated', 'Projekt geaendert'), ('project_deleted', 'Projekt geloescht'), ('part_created', 'Teil angelegt'), ('revision_uploaded', 'Revision hochgeladen'), ('revision_released', 'Revision freigegeben'), ('revision_downloaded', 'Revision heruntergeladen'), ('revision_notes_updated', 'Revisionsnotiz geaendert'), ('project_snapshot_created', 'Projektstand angelegt'), ('export_job_created', 'Exportjob angelegt'), ('export_job_failed', 'Exportjob fehlgeschlagen'), ('revision_artifact_created', 'Revisionsartefakt angelegt'), ('checkout_created', 'Checkout angelegt'), ('checkout_canceled', 'Checkout abgebrochen'), ('checkout_completed', 'Checkout eingecheckt'), ('annotation_created', 'Anmerkung angelegt'), ('annotation_updated', 'Anmerkung geaendert')], max_length=40),
        ),
    ]
