# Generated by Django 5.2.15 on 2026-07-01 07:26

import django.db.models.deletion
import plm.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0007_alter_auditevent_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('machine_type', models.CharField(choices=[('printer_3d', '3D-Drucker'), ('cnc', 'CNC'), ('laser', 'Laser'), ('external', 'Externer Fertiger'), ('other', 'Sonstige')], default='printer_3d', max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('network_address', models.CharField(blank=True, max_length=255)),
                ('integration_kind', models.CharField(blank=True, help_text='Spaeter z.B. bambulab, octoprint, moonraker oder vendor-api.', max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('project_created', 'Projekt angelegt'), ('project_updated', 'Projekt geaendert'), ('project_deleted', 'Projekt geloescht'), ('part_created', 'Teil angelegt'), ('revision_uploaded', 'Revision hochgeladen'), ('revision_released', 'Revision freigegeben'), ('revision_downloaded', 'Revision heruntergeladen'), ('revision_notes_updated', 'Revisionsnotiz geaendert'), ('project_snapshot_created', 'Projektstand angelegt'), ('export_job_created', 'Exportjob angelegt'), ('export_job_failed', 'Exportjob fehlgeschlagen'), ('revision_artifact_created', 'Revisionsartefakt angelegt'), ('manufacturing_file_uploaded', 'Fertigungsdatei hochgeladen'), ('manufacturing_file_updated', 'Fertigungsdatei geaendert'), ('manufacturing_file_status_changed', 'Fertigungsdatei-Status geaendert'), ('manufacturing_run_created', 'Fertigungslauf angelegt'), ('manufacturing_run_attachment_added', 'Fertigungslauf-Anhang angelegt'), ('checkout_created', 'Checkout angelegt'), ('checkout_canceled', 'Checkout abgebrochen'), ('checkout_completed', 'Checkout eingecheckt'), ('annotation_created', 'Anmerkung angelegt'), ('annotation_updated', 'Anmerkung geaendert')], max_length=40),
        ),
        migrations.CreateModel(
            name='ManufacturingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_type', models.CharField(choices=[('slicer_3mf', 'Slicer-3MF'), ('gcode', 'G-Code'), ('bgcode', 'Bambu/Prusa BGCode'), ('stl_print', 'STL Fertigung'), ('step_vendor', 'STEP Fertiger'), ('pdf_drawing', 'Fertigungs-PDF'), ('other', 'Sonstige')], default='slicer_3mf', max_length=30)),
                ('purpose', models.CharField(choices=[('print', '3D-Druck'), ('external_manufacturing', 'Externe Fertigung'), ('inspection', 'Pruefung'), ('documentation', 'Dokumentation')], default='print', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('approved', 'Freigegeben'), ('printed', 'Gedruckt'), ('obsolete', 'Obsolet')], default='draft', max_length=20)),
                ('file', models.FileField(max_length=500, upload_to=plm.models.manufacturing_file_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('label', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('slicer_name', models.CharField(blank=True, max_length=120)),
                ('slicer_version', models.CharField(blank=True, max_length=80)),
                ('machine_label', models.CharField(blank=True, max_length=160)),
                ('printer_profile', models.CharField(blank=True, max_length=160)),
                ('material', models.CharField(blank=True, max_length=120)),
                ('material_brand', models.CharField(blank=True, max_length=120)),
                ('nozzle_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('layer_height', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('estimated_print_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_material_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_files', to='plm.revision')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_manufacturing_files', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_files', to='plm.manufacturingmachine')),
            ],
            options={
                'ordering': ['revision__part__project__code', 'revision__part__number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('running', 'Laeuft'), ('succeeded', 'Erfolgreich'), ('failed', 'Fehlgeschlagen'), ('scrapped', 'Ausschuss')], default='planned', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('material_batch', models.CharField(blank=True, max_length=160)),
                ('result_notes', models.TextField(blank=True)),
                ('machine_report', models.JSONField(blank=True, default=dict)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='plm.manufacturingmachine')),
                ('manufacturing_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='plm.manufacturingfile')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingRunAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment_type', models.CharField(choices=[('photo', 'Foto'), ('log', 'Log'), ('report', 'Report'), ('measurement', 'Messprotokoll'), ('other', 'Sonstige')], default='photo', max_length=20)),
                ('file', models.FileField(max_length=500, upload_to=plm.models.manufacturing_run_attachment_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='plm.manufacturingrun')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_manufacturing_run_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['run', 'attachment_type', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='manufacturingfile',
            constraint=models.UniqueConstraint(fields=('revision', 'sha256'), name='unique_manufacturing_file_sha_per_revision'),
        ),
    ]
