# Generated by Django 5.2.15 on 2026-07-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0008_manufacturingmachine_alter_auditevent_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingfile',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('approved', 'Freigegeben'), ('printed', 'Gedruckt'), ('obsolete', 'Obsolet')], default='approved', max_length=20),
        ),
    ]
