# Generated by Django 5.2.15 on 2026-07-01 18:32

import plm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0009_alter_manufacturingfile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingfile',
            name='thumbnail',
            field=models.FileField(blank=True, max_length=500, upload_to=plm.models.manufacturing_thumbnail_upload_path),
        ),
        migrations.AddField(
            model_name='manufacturingfile',
            name='thumbnail_original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
