# Generated by Django 5.2.15 on 2026-08-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0018_annotation_viewer_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('project_created', 'Projekt angelegt'), ('project_updated', 'Projekt geaendert'), ('project_deleted', 'Projekt geloescht'), ('part_created', 'Teil angelegt'), ('revision_uploaded', 'Revision hochgeladen'), ('revision_released', 'Revision freigegeben'), ('revision_obsoleted', 'Revision obsolet gesetzt'), ('revision_downloaded', 'Revision heruntergeladen'), ('revision_notes_updated', 'Revisionsnotiz geaendert'), ('project_snapshot_created', 'Projektstand angelegt'), ('export_job_created', 'Exportjob angelegt'), ('export_job_failed', 'Exportjob fehlgeschlagen'), ('revision_artifact_created', 'Revisionsartefakt angelegt'), ('manufacturing_file_uploaded', 'Fertigungsdatei hochgeladen'), ('manufacturing_file_downloaded', 'Fertigungsdatei heruntergeladen'), ('manufacturing_file_updated', 'Fertigungsdatei geaendert'), ('manufacturing_file_status_changed', 'Fertigungsdatei-Status geaendert'), ('bambuddy_source_attached', '3MF an Bambuddy-Druck angehängt'), ('manufacturing_run_created', 'Fertigungslauf angelegt'), ('manufacturing_run_attachment_added', 'Fertigungslauf-Anhang angelegt'), ('checkout_created', 'Checkout angelegt'), ('checkout_file_added', 'Teil zu Checkout hinzugefügt'), ('checkout_file_removed', 'Teil aus Checkout entfernt'), ('checkout_canceled', 'Checkout abgebrochen'), ('checkout_completed', 'Checkout eingecheckt'), ('annotation_created', 'Anmerkung angelegt'), ('annotation_updated', 'Anmerkung geaendert'), ('annotation_deleted', 'Anmerkung geloescht'), ('user_created', 'Benutzer angelegt'), ('user_updated', 'Benutzer geaendert'), ('user_password_set', 'Benutzerpasswort gesetzt'), ('api_token_created', 'API-Token angelegt'), ('api_token_updated', 'API-Token geaendert'), ('api_token_revoked', 'API-Token widerrufen')], max_length=40),
        ),
    ]
