from django.contrib.auth import views as auth_views
from django.urls import path

from . import api, views

app_name = "plm"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="plm/login.html",
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path("", views.project_list, name="project_list"),
    path("logout/", views.logout_view, name="logout"),
    path(
        "jobs/status/",
        views.user_export_jobs_status,
        name="user_export_jobs_status",
    ),
    path("verwaltung/", views.user_management_list, name="user_management"),
    path("verwaltung/users/new/", views.create_user, name="create_user"),
    path("verwaltung/users/<int:user_id>/edit/", views.edit_user, name="edit_user"),
    path(
        "verwaltung/users/<int:user_id>/password/",
        views.set_user_password,
        name="set_user_password",
    ),
    path(
        "verwaltung/users/<int:user_id>/tokens/new/",
        views.create_user_token,
        name="create_user_token",
    ),
    path(
        "verwaltung/tokens/<int:token_id>/edit/",
        views.edit_api_token,
        name="edit_api_token",
    ),
    path(
        "verwaltung/tokens/<int:token_id>/revoke/",
        views.revoke_api_token,
        name="revoke_api_token",
    ),
    path("projects/new/", views.create_project, name="create_project"),
    path("projects/<int:project_id>/", views.project_detail, name="project_detail"),
    path(
        "projects/<int:project_id>/properties/",
        views.project_properties,
        name="project_properties",
    ),
    path("projects/<int:project_id>/edit/", views.edit_project, name="edit_project"),
    path(
        "projects/<int:project_id>/delete/",
        views.delete_project,
        name="delete_project",
    ),
    path(
        "projects/<int:project_id>/snapshots/upload/",
        views.upload_project_snapshot,
        name="upload_project_snapshot",
    ),
    path("projects/<int:project_id>/parts/new/", views.create_part, name="create_part"),
    path("parts/<int:part_id>/", views.part_detail, name="part_detail"),
    path(
        "parts/<int:part_id>/properties/",
        views.part_properties,
        name="part_properties",
    ),
    path(
        "parts/<int:part_id>/jobs/process/",
        views.process_export_jobs_once,
        name="process_export_jobs_once",
    ),
    path("parts/<int:part_id>/upload/", views.upload_revision, name="upload_revision"),
    path(
        "parts/<int:part_id>/upload/confirm/",
        views.confirm_revision_upload,
        name="confirm_revision_upload",
    ),
    path(
        "revisions/<int:revision_id>/download/",
        views.download_revision,
        name="download_revision",
    ),
    path(
        "revisions/<int:revision_id>/properties/",
        views.revision_properties,
        name="revision_properties",
    ),
    path(
        "revisions/<int:revision_id>/release/",
        views.release_revision_view,
        name="release_revision",
    ),
    path(
        "revisions/<int:revision_id>/notes/",
        views.update_revision_notes,
        name="update_revision_notes",
    ),
    path(
        "revisions/<int:revision_id>/inspect/",
        views.create_revision_inspect_job,
        name="create_revision_inspect_job",
    ),
    path(
        "revisions/<int:revision_id>/exports/new/",
        views.create_revision_export_job,
        name="create_revision_export_job",
    ),
    path(
        "revisions/<int:revision_id>/png-views/",
        views.create_revision_png_job,
        name="create_revision_png_job",
    ),
    path(
        "revisions/<int:revision_id>/viewer-preview/",
        views.create_revision_viewer_preview,
        name="create_revision_viewer_preview",
    ),
    path(
        "revisions/<int:revision_id>/viewer-status/",
        views.revision_viewer_status,
        name="revision_viewer_status",
    ),
    path(
        "revisions/<int:revision_id>/viewer-source/",
        views.revision_viewer_source,
        name="revision_viewer_source",
    ),
    path(
        "artifacts/<int:artifact_id>/download/",
        views.download_revision_artifact,
        name="download_revision_artifact",
    ),
    path(
        "artifacts/<int:artifact_id>/viewer-source/",
        views.artifact_viewer_source,
        name="artifact_viewer_source",
    ),
    path(
        "revisions/<int:revision_id>/manufacturing-files/upload/",
        views.upload_manufacturing_file,
        name="upload_manufacturing_file",
    ),
    path(
        "manufacturing-files/<int:manufacturing_file_id>/download/",
        views.download_manufacturing_file,
        name="download_manufacturing_file",
    ),
    path(
        "manufacturing-files/<int:manufacturing_file_id>/viewer-source/",
        views.manufacturing_file_viewer_source,
        name="manufacturing_file_viewer_source",
    ),
    path(
        "manufacturing-files/<int:manufacturing_file_id>/thumbnail/",
        views.manufacturing_file_thumbnail,
        name="manufacturing_file_thumbnail",
    ),
    path(
        "manufacturing-files/<int:manufacturing_file_id>/obsolete/",
        views.obsolete_manufacturing_file,
        name="obsolete_manufacturing_file",
    ),
    path(
        "parts/<int:part_id>/compare/",
        views.revision_compare,
        name="revision_compare",
    ),
    path(
        "parts/<int:part_id>/compare/status/",
        views.revision_compare_status,
        name="revision_compare_status",
    ),
    path(
        "snapshots/<int:snapshot_id>/download/",
        views.download_project_snapshot,
        name="download_project_snapshot",
    ),
    path("api/projects/", api.projects_api, name="api_projects"),
    path("api/projects/import/", api.project_import_api, name="api_project_import"),
    path("api/projects/<int:project_id>/", api.project_api, name="api_project"),
    path(
        "api/projects/<int:project_id>/snapshots/import/",
        api.project_snapshot_import_api,
        name="api_project_snapshot_import",
    ),
    path(
        "api/projects/<int:project_id>/parts/",
        api.project_parts_api,
        name="api_project_parts",
    ),
    path("api/parts/<int:part_id>/", api.part_api, name="api_part"),
    path(
        "api/parts/<int:part_id>/annotations/",
        api.part_annotations_api,
        name="api_part_annotations",
    ),
    path(
        "api/revisions/<int:revision_id>/",
        api.revision_api,
        name="api_revision",
    ),
    path(
        "api/revisions/<int:revision_id>/notes/",
        api.revision_notes_api,
        name="api_revision_notes",
    ),
    path(
        "api/revisions/<int:revision_id>/file/",
        api.revision_file_api,
        name="api_revision_file",
    ),
    path(
        "api/revisions/<int:revision_id>/manifest/",
        api.revision_manifest_api,
        name="api_revision_manifest",
    ),
    path(
        "api/revisions/<int:revision_id>/checkout/",
        api.revision_checkout_api,
        name="api_revision_checkout",
    ),
    path(
        "api/checkouts/active/",
        api.active_checkouts_api,
        name="api_active_checkouts",
    ),
    path(
        "api/checkouts/<int:checkout_id>/manifest/",
        api.checkout_manifest_api,
        name="api_checkout_manifest",
    ),
    path(
        "api/checkouts/<int:checkout_id>/cancel/",
        api.checkout_cancel_api,
        name="api_checkout_cancel",
    ),
    path(
        "api/checkouts/<int:checkout_id>/checkin/",
        api.checkout_checkin_api,
        name="api_checkout_checkin",
    ),
    path(
        "api/annotations/<int:annotation_id>/",
        api.annotation_api,
        name="api_annotation",
    ),
]
